#!/bin/bash

# Run the format plugin command, telling it to detect and use modified files only.
swift package plugin --allow-writing-to-package-directory format --modified-only

# Commit all modified files.
# TODO: This will add all files to the commit, regardless!
# git add .
